//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace J4ni.Controls.LoginRegRevRateMgmtServiceProxy {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string firstNameField;
        
        private string genderField;
        
        private string lastNameField;
        
        private string nationalityField;
        
        private string prefferedlanguageField;
        
        private string pwdField;
        
        private string unameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.nationalityField, value) != true)) {
                    this.nationalityField = value;
                    this.RaisePropertyChanged("nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prefferedlanguage {
            get {
                return this.prefferedlanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.prefferedlanguageField, value) != true)) {
                    this.prefferedlanguageField = value;
                    this.RaisePropertyChanged("prefferedlanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pwd {
            get {
                return this.pwdField;
            }
            set {
                if ((object.ReferenceEquals(this.pwdField, value) != true)) {
                    this.pwdField = value;
                    this.RaisePropertyChanged("pwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uname {
            get {
                return this.unameField;
            }
            set {
                if ((object.ReferenceEquals(this.unameField, value) != true)) {
                    this.unameField = value;
                    this.RaisePropertyChanged("uname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAuthInfo", Namespace="http://schemas.datacontract.org/2004/07/Domain.DataContracts.DTOs")]
    public partial class UserAuthInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string NationalityField;
        
        private string PasswordField;
        
        private string Preferred_LanguageField;
        
        private string UserNameField;
        
        private J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserTypes UserTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Preferred_Language {
            get {
                return this.Preferred_LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.Preferred_LanguageField, value) != true)) {
                    this.Preferred_LanguageField = value;
                    this.RaisePropertyChanged("Preferred_Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserTypes UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTypes", Namespace="http://schemas.datacontract.org/2004/07/Domain.DataContracts")]
    public enum UserTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tourist = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogInResult", Namespace="http://schemas.datacontract.org/2004/07/DistributedServices.Contracts")]
    public partial class LogInResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private bool isSucceededField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageField, value) != true)) {
                    this.errorMessageField = value;
                    this.RaisePropertyChanged("errorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSucceeded {
            get {
                return this.isSucceededField;
            }
            set {
                if ((this.isSucceededField.Equals(value) != true)) {
                    this.isSucceededField = value;
                    this.RaisePropertyChanged("isSucceeded");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateInfo", Namespace="http://schemas.datacontract.org/2004/07/DistributedServices.Contracts")]
    public partial class RateInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string HOTSPOTIDField;
        
        private double RATEField;
        
        private string USERNAMEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HOTSPOTID {
            get {
                return this.HOTSPOTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HOTSPOTIDField, value) != true)) {
                    this.HOTSPOTIDField = value;
                    this.RaisePropertyChanged("HOTSPOTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RATE {
            get {
                return this.RATEField;
            }
            set {
                if ((this.RATEField.Equals(value) != true)) {
                    this.RATEField = value;
                    this.RaisePropertyChanged("RATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERNAME {
            get {
                return this.USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERNAMEField, value) != true)) {
                    this.USERNAMEField = value;
                    this.RaisePropertyChanged("USERNAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateResultReview", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.CommonCotracts")]
    public partial class RateResultReview : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double RateField;
        
        private string errorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageField, value) != true)) {
                    this.errorMessageField = value;
                    this.RaisePropertyChanged("errorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewInfo", Namespace="http://schemas.datacontract.org/2004/07/DistributedServices.Contracts")]
    public partial class ReviewInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string HotspotidField;
        
        private string UserNameField;
        
        private string UserreviewField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hotspotid {
            get {
                return this.HotspotidField;
            }
            set {
                if ((object.ReferenceEquals(this.HotspotidField, value) != true)) {
                    this.HotspotidField = value;
                    this.RaisePropertyChanged("Hotspotid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Userreview {
            get {
                return this.UserreviewField;
            }
            set {
                if ((object.ReferenceEquals(this.UserreviewField, value) != true)) {
                    this.UserreviewField = value;
                    this.RaisePropertyChanged("Userreview");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.CommonCotracts")]
    public partial class OperationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorMessageField;
        
        private bool OperationStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperationStatus {
            get {
                return this.OperationStatusField;
            }
            set {
                if ((this.OperationStatusField.Equals(value) != true)) {
                    this.OperationStatusField = value;
                    this.RaisePropertyChanged("OperationStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService")]
    public interface ILoginRegRevRateMgmtService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginRegRevRateMgmtService/RegisterUser", ReplyAction="http://tempuri.org/ILoginRegRevRateMgmtService/RegisterUserResponse")]
        System.IAsyncResult BeginRegisterUser(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserInfo xList, System.AsyncCallback callback, object asyncState);
        
        string EndRegisterUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginRegRevRateMgmtService/LogIn", ReplyAction="http://tempuri.org/ILoginRegRevRateMgmtService/LogInResponse")]
        System.IAsyncResult BeginLogIn(ref J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo, System.AsyncCallback callback, object asyncState);
        
        J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult EndLogIn(ref J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo, System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginRegRevRateMgmtService/Rate", ReplyAction="http://tempuri.org/ILoginRegRevRateMgmtService/RateResponse")]
        System.IAsyncResult BeginRate(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateInfo rateInfo, System.AsyncCallback callback, object asyncState);
        
        J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview EndRate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ILoginRegRevRateMgmtService/PostReview", ReplyAction="http://tempuri.org/ILoginRegRevRateMgmtService/PostReviewResponse")]
        System.IAsyncResult BeginPostReview(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ReviewInfo reviewInfo, System.AsyncCallback callback, object asyncState);
        
        J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult EndPostReview(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginRegRevRateMgmtServiceChannel : J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogInCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo {
            get {
                base.RaiseExceptionIfNecessary();
                return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo)(this.results[0]));
            }
        }
        
        public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PostReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginRegRevRateMgmtServiceClient : System.ServiceModel.ClientBase<J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService>, J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService {
        
        private BeginOperationDelegate onBeginRegisterUserDelegate;
        
        private EndOperationDelegate onEndRegisterUserDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogInDelegate;
        
        private EndOperationDelegate onEndLogInDelegate;
        
        private System.Threading.SendOrPostCallback onLogInCompletedDelegate;
        
        private BeginOperationDelegate onBeginRateDelegate;
        
        private EndOperationDelegate onEndRateDelegate;
        
        private System.Threading.SendOrPostCallback onRateCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostReviewDelegate;
        
        private EndOperationDelegate onEndPostReviewDelegate;
        
        private System.Threading.SendOrPostCallback onPostReviewCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public LoginRegRevRateMgmtServiceClient() {
        }
        
        public LoginRegRevRateMgmtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginRegRevRateMgmtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginRegRevRateMgmtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginRegRevRateMgmtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RegisterUserCompletedEventArgs> RegisterUserCompleted;
        
        public event System.EventHandler<LogInCompletedEventArgs> LogInCompleted;
        
        public event System.EventHandler<RateCompletedEventArgs> RateCompleted;
        
        public event System.EventHandler<PostReviewCompletedEventArgs> PostReviewCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.BeginRegisterUser(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserInfo xList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterUser(xList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.EndRegisterUser(System.IAsyncResult result) {
            return base.Channel.EndRegisterUser(result);
        }
        
        private System.IAsyncResult OnBeginRegisterUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserInfo xList = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserInfo)(inValues[0]));
            return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).BeginRegisterUser(xList, callback, asyncState);
        }
        
        private object[] OnEndRegisterUser(System.IAsyncResult result) {
            string retVal = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).EndRegisterUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterUserCompleted(object state) {
            if ((this.RegisterUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterUserCompleted(this, new RegisterUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterUserAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserInfo xList) {
            this.RegisterUserAsync(xList, null);
        }
        
        public void RegisterUserAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserInfo xList, object userState) {
            if ((this.onBeginRegisterUserDelegate == null)) {
                this.onBeginRegisterUserDelegate = new BeginOperationDelegate(this.OnBeginRegisterUser);
            }
            if ((this.onEndRegisterUserDelegate == null)) {
                this.onEndRegisterUserDelegate = new EndOperationDelegate(this.OnEndRegisterUser);
            }
            if ((this.onRegisterUserCompletedDelegate == null)) {
                this.onRegisterUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterUserCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterUserDelegate, new object[] {
                        xList}, this.onEndRegisterUserDelegate, this.onRegisterUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.BeginLogIn(ref J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogIn(ref userAuthInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.EndLogIn(ref J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo, System.IAsyncResult result) {
            return base.Channel.EndLogIn(ref userAuthInfo, result);
        }
        
        private System.IAsyncResult OnBeginLogIn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo)(inValues[0]));
            return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).BeginLogIn(ref userAuthInfo, callback, asyncState);
        }
        
        private object[] OnEndLogIn(System.IAsyncResult result) {
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo = this.GetDefaultValueForInitialization<J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo>();
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult retVal = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).EndLogIn(ref userAuthInfo, result);
            return new object[] {
                    userAuthInfo,
                    retVal};
        }
        
        private void OnLogInCompleted(object state) {
            if ((this.LogInCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogInCompleted(this, new LogInCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogInAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo) {
            this.LogInAsync(userAuthInfo, null);
        }
        
        public void LogInAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo, object userState) {
            if ((this.onBeginLogInDelegate == null)) {
                this.onBeginLogInDelegate = new BeginOperationDelegate(this.OnBeginLogIn);
            }
            if ((this.onEndLogInDelegate == null)) {
                this.onEndLogInDelegate = new EndOperationDelegate(this.OnEndLogIn);
            }
            if ((this.onLogInCompletedDelegate == null)) {
                this.onLogInCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogInCompleted);
            }
            base.InvokeAsync(this.onBeginLogInDelegate, new object[] {
                        userAuthInfo}, this.onEndLogInDelegate, this.onLogInCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.BeginRate(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateInfo rateInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRate(rateInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.EndRate(System.IAsyncResult result) {
            return base.Channel.EndRate(result);
        }
        
        private System.IAsyncResult OnBeginRate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateInfo rateInfo = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateInfo)(inValues[0]));
            return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).BeginRate(rateInfo, callback, asyncState);
        }
        
        private object[] OnEndRate(System.IAsyncResult result) {
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview retVal = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).EndRate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRateCompleted(object state) {
            if ((this.RateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RateCompleted(this, new RateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RateAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateInfo rateInfo) {
            this.RateAsync(rateInfo, null);
        }
        
        public void RateAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateInfo rateInfo, object userState) {
            if ((this.onBeginRateDelegate == null)) {
                this.onBeginRateDelegate = new BeginOperationDelegate(this.OnBeginRate);
            }
            if ((this.onEndRateDelegate == null)) {
                this.onEndRateDelegate = new EndOperationDelegate(this.OnEndRate);
            }
            if ((this.onRateCompletedDelegate == null)) {
                this.onRateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRateCompleted);
            }
            base.InvokeAsync(this.onBeginRateDelegate, new object[] {
                        rateInfo}, this.onEndRateDelegate, this.onRateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.BeginPostReview(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ReviewInfo reviewInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostReview(reviewInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService.EndPostReview(System.IAsyncResult result) {
            return base.Channel.EndPostReview(result);
        }
        
        private System.IAsyncResult OnBeginPostReview(object[] inValues, System.AsyncCallback callback, object asyncState) {
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ReviewInfo reviewInfo = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ReviewInfo)(inValues[0]));
            return ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).BeginPostReview(reviewInfo, callback, asyncState);
        }
        
        private object[] OnEndPostReview(System.IAsyncResult result) {
            J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult retVal = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService)(this)).EndPostReview(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPostReviewCompleted(object state) {
            if ((this.PostReviewCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostReviewCompleted(this, new PostReviewCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostReviewAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ReviewInfo reviewInfo) {
            this.PostReviewAsync(reviewInfo, null);
        }
        
        public void PostReviewAsync(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ReviewInfo reviewInfo, object userState) {
            if ((this.onBeginPostReviewDelegate == null)) {
                this.onBeginPostReviewDelegate = new BeginOperationDelegate(this.OnBeginPostReview);
            }
            if ((this.onEndPostReviewDelegate == null)) {
                this.onEndPostReviewDelegate = new EndOperationDelegate(this.OnEndPostReview);
            }
            if ((this.onPostReviewCompletedDelegate == null)) {
                this.onPostReviewCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostReviewCompleted);
            }
            base.InvokeAsync(this.onBeginPostReviewDelegate, new object[] {
                        reviewInfo}, this.onEndPostReviewDelegate, this.onPostReviewCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService CreateChannel() {
            return new LoginRegRevRateMgmtServiceClientChannel(this);
        }
        
        private class LoginRegRevRateMgmtServiceClientChannel : ChannelBase<J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService>, J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService {
            
            public LoginRegRevRateMgmtServiceClientChannel(System.ServiceModel.ClientBase<J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ILoginRegRevRateMgmtService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegisterUser(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserInfo xList, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = xList;
                System.IAsyncResult _result = base.BeginInvoke("RegisterUser", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRegisterUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RegisterUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogIn(ref J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userAuthInfo;
                System.IAsyncResult _result = base.BeginInvoke("LogIn", _args, callback, asyncState);
                userAuthInfo = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo)(_args[0]));
                return _result;
            }
            
            public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult EndLogIn(ref J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo userAuthInfo, System.IAsyncResult result) {
                object[] _args = new object[1];
                _args[0] = userAuthInfo;
                J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult _result = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.LogInResult)(base.EndInvoke("LogIn", _args, result)));
                userAuthInfo = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.UserAuthInfo)(_args[0]));
                return _result;
            }
            
            public System.IAsyncResult BeginRate(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateInfo rateInfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = rateInfo;
                System.IAsyncResult _result = base.BeginInvoke("Rate", _args, callback, asyncState);
                return _result;
            }
            
            public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview EndRate(System.IAsyncResult result) {
                object[] _args = new object[0];
                J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview _result = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.RateResultReview)(base.EndInvoke("Rate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPostReview(J4ni.Controls.LoginRegRevRateMgmtServiceProxy.ReviewInfo reviewInfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = reviewInfo;
                System.IAsyncResult _result = base.BeginInvoke("PostReview", _args, callback, asyncState);
                return _result;
            }
            
            public J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult EndPostReview(System.IAsyncResult result) {
                object[] _args = new object[0];
                J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult _result = ((J4ni.Controls.LoginRegRevRateMgmtServiceProxy.OperationResult)(base.EndInvoke("PostReview", _args, result)));
                return _result;
            }
        }
    }
}
