//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;



using ITI.Common.Utilities.Data.Core;
using Domain.DataContracts;

namespace ITI.Nlayerd.Infrastructure.Data.UTour.UnitOfWork
{
    
    ///<sumary>
    ///Base contract for context in ATM Module, this is a marker interface. 
    ///</sumary>
    public interface IUTourUnitOfWork :IQueryableUnitOfWork
    {
       
        #region ObjectSet Properties
    
    	IObjectSet<Admin_Users> Admin_Users{get;}
    	
    
    	IObjectSet<city> cities{get;}
    	
    
    	IObjectSet<LayerTable> LayerTables{get;}
    	
    
    	IObjectSet<Monument_Ratings> Monument_Ratings{get;}
    	
    
    	IObjectSet<Monuments_Photos> Monuments_Photos{get;}
    	
    
    	IObjectSet<Monuments_Reviews> Monuments_Reviews{get;}
    	
    
    	IObjectSet<Monuments_Videos> Monuments_Videos{get;}
    	
    
    	IObjectSet<sysdiagram> sysdiagrams{get;}
    	
    
    	IObjectSet<Tourist> Tourists{get;}
    	
    
    	IObjectSet<webpages_Membership> webpages_Membership{get;}
    	
    
    	IObjectSet<webpages_OAuthMembership> webpages_OAuthMembership{get;}
    	
    
    	IObjectSet<webpages_Roles> webpages_Roles{get;}
    	
    
    	IObjectSet<UserProfile> UserProfiles{get;}
    	
    
    	IObjectSet<UploadedPhoto> UploadedPhotos{get;}
    	
    
    	IObjectSet<layerhotspot> layerhotspots{get;}
    	

        #endregion

    
    }
}
	
