//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Test.HotSpotsMgmtService.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LayerInfo", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo")]
    [System.SerializableAttribute()]
    public partial class LayerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.Actions[] actionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string biwStyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.HotSpots[] deletedHotspotsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool fullRefreshField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.HotSpots[] hotspotsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string layerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool morePagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nextPageKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int radiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int refreshDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int refreshIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string showMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.Actions[] actions {
            get {
                return this.actionsField;
            }
            set {
                if ((object.ReferenceEquals(this.actionsField, value) != true)) {
                    this.actionsField = value;
                    this.RaisePropertyChanged("actions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biwStyle {
            get {
                return this.biwStyleField;
            }
            set {
                if ((object.ReferenceEquals(this.biwStyleField, value) != true)) {
                    this.biwStyleField = value;
                    this.RaisePropertyChanged("biwStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.HotSpots[] deletedHotspots {
            get {
                return this.deletedHotspotsField;
            }
            set {
                if ((object.ReferenceEquals(this.deletedHotspotsField, value) != true)) {
                    this.deletedHotspotsField = value;
                    this.RaisePropertyChanged("deletedHotspots");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeField, value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorString {
            get {
                return this.errorStringField;
            }
            set {
                if ((object.ReferenceEquals(this.errorStringField, value) != true)) {
                    this.errorStringField = value;
                    this.RaisePropertyChanged("errorString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool fullRefresh {
            get {
                return this.fullRefreshField;
            }
            set {
                if ((this.fullRefreshField.Equals(value) != true)) {
                    this.fullRefreshField = value;
                    this.RaisePropertyChanged("fullRefresh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.HotSpots[] hotspots {
            get {
                return this.hotspotsField;
            }
            set {
                if ((object.ReferenceEquals(this.hotspotsField, value) != true)) {
                    this.hotspotsField = value;
                    this.RaisePropertyChanged("hotspots");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string layer {
            get {
                return this.layerField;
            }
            set {
                if ((object.ReferenceEquals(this.layerField, value) != true)) {
                    this.layerField = value;
                    this.RaisePropertyChanged("layer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool morePages {
            get {
                return this.morePagesField;
            }
            set {
                if ((this.morePagesField.Equals(value) != true)) {
                    this.morePagesField = value;
                    this.RaisePropertyChanged("morePages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nextPageKey {
            get {
                return this.nextPageKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.nextPageKeyField, value) != true)) {
                    this.nextPageKeyField = value;
                    this.RaisePropertyChanged("nextPageKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int radius {
            get {
                return this.radiusField;
            }
            set {
                if ((this.radiusField.Equals(value) != true)) {
                    this.radiusField = value;
                    this.RaisePropertyChanged("radius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int refreshDistance {
            get {
                return this.refreshDistanceField;
            }
            set {
                if ((this.refreshDistanceField.Equals(value) != true)) {
                    this.refreshDistanceField = value;
                    this.RaisePropertyChanged("refreshDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int refreshInterval {
            get {
                return this.refreshIntervalField;
            }
            set {
                if ((this.refreshIntervalField.Equals(value) != true)) {
                    this.refreshIntervalField = value;
                    this.RaisePropertyChanged("refreshInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string showMessage {
            get {
                return this.showMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.showMessageField, value) != true)) {
                    this.showMessageField = value;
                    this.RaisePropertyChanged("showMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actions", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class Actions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string activityMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.ActivityType activityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool autoTriggerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool autoTriggerOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int autoTriggerRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool closeBiwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string methodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] paramsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool showActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string activityMessage {
            get {
                return this.activityMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.activityMessageField, value) != true)) {
                    this.activityMessageField = value;
                    this.RaisePropertyChanged("activityMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.ActivityType activityType {
            get {
                return this.activityTypeField;
            }
            set {
                if ((this.activityTypeField.Equals(value) != true)) {
                    this.activityTypeField = value;
                    this.RaisePropertyChanged("activityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool autoTrigger {
            get {
                return this.autoTriggerField;
            }
            set {
                if ((this.autoTriggerField.Equals(value) != true)) {
                    this.autoTriggerField = value;
                    this.RaisePropertyChanged("autoTrigger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool autoTriggerOnly {
            get {
                return this.autoTriggerOnlyField;
            }
            set {
                if ((this.autoTriggerOnlyField.Equals(value) != true)) {
                    this.autoTriggerOnlyField = value;
                    this.RaisePropertyChanged("autoTriggerOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int autoTriggerRange {
            get {
                return this.autoTriggerRangeField;
            }
            set {
                if ((this.autoTriggerRangeField.Equals(value) != true)) {
                    this.autoTriggerRangeField = value;
                    this.RaisePropertyChanged("autoTriggerRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool closeBiw {
            get {
                return this.closeBiwField;
            }
            set {
                if ((this.closeBiwField.Equals(value) != true)) {
                    this.closeBiwField = value;
                    this.RaisePropertyChanged("closeBiw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.contentTypeField, value) != true)) {
                    this.contentTypeField = value;
                    this.RaisePropertyChanged("contentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string method {
            get {
                return this.methodField;
            }
            set {
                if ((object.ReferenceEquals(this.methodField, value) != true)) {
                    this.methodField = value;
                    this.RaisePropertyChanged("method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] @params {
            get {
                return this.paramsField;
            }
            set {
                if ((object.ReferenceEquals(this.paramsField, value) != true)) {
                    this.paramsField = value;
                    this.RaisePropertyChanged("params");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool showActivity {
            get {
                return this.showActivityField;
            }
            set {
                if ((this.showActivityField.Equals(value) != true)) {
                    this.showActivityField = value;
                    this.RaisePropertyChanged("showActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                if ((object.ReferenceEquals(this.uriField, value) != true)) {
                    this.uriField = value;
                    this.RaisePropertyChanged("uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotSpots", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class HotSpots : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.Actions[] actionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.Anchor anchorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.Animations animationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string biwStyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool inFocusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference._Object objectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool showBiwOnClickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool showSmallBiwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.Text textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.Transform transformField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.Actions[] actions {
            get {
                return this.actionsField;
            }
            set {
                if ((object.ReferenceEquals(this.actionsField, value) != true)) {
                    this.actionsField = value;
                    this.RaisePropertyChanged("actions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.Anchor anchor {
            get {
                return this.anchorField;
            }
            set {
                if ((object.ReferenceEquals(this.anchorField, value) != true)) {
                    this.anchorField = value;
                    this.RaisePropertyChanged("anchor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.Animations animations {
            get {
                return this.animationsField;
            }
            set {
                if ((object.ReferenceEquals(this.animationsField, value) != true)) {
                    this.animationsField = value;
                    this.RaisePropertyChanged("animations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biwStyle {
            get {
                return this.biwStyleField;
            }
            set {
                if ((object.ReferenceEquals(this.biwStyleField, value) != true)) {
                    this.biwStyleField = value;
                    this.RaisePropertyChanged("biwStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imageURL {
            get {
                return this.imageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.imageURLField, value) != true)) {
                    this.imageURLField = value;
                    this.RaisePropertyChanged("imageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool inFocus {
            get {
                return this.inFocusField;
            }
            set {
                if ((this.inFocusField.Equals(value) != true)) {
                    this.inFocusField = value;
                    this.RaisePropertyChanged("inFocus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference._Object @object {
            get {
                return this.objectField;
            }
            set {
                if ((object.ReferenceEquals(this.objectField, value) != true)) {
                    this.objectField = value;
                    this.RaisePropertyChanged("object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool showBiwOnClick {
            get {
                return this.showBiwOnClickField;
            }
            set {
                if ((this.showBiwOnClickField.Equals(value) != true)) {
                    this.showBiwOnClickField = value;
                    this.RaisePropertyChanged("showBiwOnClick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool showSmallBiw {
            get {
                return this.showSmallBiwField;
            }
            set {
                if ((this.showSmallBiwField.Equals(value) != true)) {
                    this.showSmallBiwField = value;
                    this.RaisePropertyChanged("showSmallBiw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.Text text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.Transform transform {
            get {
                return this.transformField;
            }
            set {
                if ((object.ReferenceEquals(this.transformField, value) != true)) {
                    this.transformField = value;
                    this.RaisePropertyChanged("transform");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityType", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    public enum ActivityType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Audio = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Video = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Phone_Call = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email_Message = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Position_Map_Navigate = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remove = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Edit = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Collect = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Play_Song = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Play_In_Game = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Share_Post_Publish = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pin_Mark_On_Map = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Check_In_Out = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Log_In_Out = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lock_Unlock = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        List_Scores = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Money_Pay_Buy = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Open = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Close = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Switch_2_Layer = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Increase_Decrease = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        View_Examine_Details = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add_2_Favorites = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kill_Hit_Attack = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Heal = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Defend = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Repair = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Use_Interact_Switch = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Animate = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scoreboard = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Generic_Action = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 36,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anchor", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class Anchor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.GeoLocation geolocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.GeoLocation geolocation {
            get {
                return this.geolocationField;
            }
            set {
                if ((object.ReferenceEquals(this.geolocationField, value) != true)) {
                    this.geolocationField = value;
                    this.RaisePropertyChanged("geolocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Animations", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class Animations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_Object", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class _Object : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Text", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class Text : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string footnoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longdescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.Photo[] photosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.review[] reviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Services.Test.HotSpotsMgmtService.ServiceReference.video[] videosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string footnote {
            get {
                return this.footnoteField;
            }
            set {
                if ((object.ReferenceEquals(this.footnoteField, value) != true)) {
                    this.footnoteField = value;
                    this.RaisePropertyChanged("footnote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string longdescription {
            get {
                return this.longdescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.longdescriptionField, value) != true)) {
                    this.longdescriptionField = value;
                    this.RaisePropertyChanged("longdescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.Photo[] photos {
            get {
                return this.photosField;
            }
            set {
                if ((object.ReferenceEquals(this.photosField, value) != true)) {
                    this.photosField = value;
                    this.RaisePropertyChanged("photos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                if ((object.ReferenceEquals(this.rateField, value) != true)) {
                    this.rateField = value;
                    this.RaisePropertyChanged("rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.review[] reviews {
            get {
                return this.reviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewsField, value) != true)) {
                    this.reviewsField = value;
                    this.RaisePropertyChanged("reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Services.Test.HotSpotsMgmtService.ServiceReference.video[] videos {
            get {
                return this.videosField;
            }
            set {
                if ((object.ReferenceEquals(this.videosField, value) != true)) {
                    this.videosField = value;
                    this.RaisePropertyChanged("videos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transform", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class Transform : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoLocation", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class GeoLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string altField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alt {
            get {
                return this.altField;
            }
            set {
                if ((object.ReferenceEquals(this.altField, value) != true)) {
                    this.altField = value;
                    this.RaisePropertyChanged("alt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lat {
            get {
                return this.latField;
            }
            set {
                if ((object.ReferenceEquals(this.latField, value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lon {
            get {
                return this.lonField;
            }
            set {
                if ((object.ReferenceEquals(this.lonField, value) != true)) {
                    this.lonField = value;
                    this.RaisePropertyChanged("lon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photo", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class Photo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.contentTypeField, value) != true)) {
                    this.contentTypeField = value;
                    this.RaisePropertyChanged("contentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="review", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usercommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usercomment {
            get {
                return this.usercommentField;
            }
            set {
                if ((object.ReferenceEquals(this.usercommentField, value) != true)) {
                    this.usercommentField = value;
                    this.RaisePropertyChanged("usercomment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="video", Namespace="http://schemas.datacontract.org/2004/07/ITI.Common.HotSpotsInfo.LayerClasses")]
    [System.SerializableAttribute()]
    public partial class video : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.contentTypeField, value) != true)) {
                    this.contentTypeField = value;
                    this.RaisePropertyChanged("contentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string length {
            get {
                return this.lengthField;
            }
            set {
                if ((object.ReferenceEquals(this.lengthField, value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotSpotsMgmtService.ServiceReference.IHotSpotsManagmentContract")]
    public interface IHotSpotsManagmentContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotSpotsManagmentContract/RetrieveHotSpots", ReplyAction="http://tempuri.org/IHotSpotsManagmentContract/RetrieveHotSpotsResponse")]
        Services.Test.HotSpotsMgmtService.ServiceReference.LayerInfo RetrieveHotSpots(string lang, string countryCode, string lon, string userId, string developerId, string developerHash, string version, string radius, string timestamp, string lat, string layerName, string accuracy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotSpotsManagmentContractChannel : Services.Test.HotSpotsMgmtService.ServiceReference.IHotSpotsManagmentContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotSpotsManagmentContractClient : System.ServiceModel.ClientBase<Services.Test.HotSpotsMgmtService.ServiceReference.IHotSpotsManagmentContract>, Services.Test.HotSpotsMgmtService.ServiceReference.IHotSpotsManagmentContract {
        
        public HotSpotsManagmentContractClient() {
        }
        
        public HotSpotsManagmentContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotSpotsManagmentContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotSpotsManagmentContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotSpotsManagmentContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Services.Test.HotSpotsMgmtService.ServiceReference.LayerInfo RetrieveHotSpots(string lang, string countryCode, string lon, string userId, string developerId, string developerHash, string version, string radius, string timestamp, string lat, string layerName, string accuracy) {
            return base.Channel.RetrieveHotSpots(lang, countryCode, lon, userId, developerId, developerHash, version, radius, timestamp, lat, layerName, accuracy);
        }
    }
}
