//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Common.Utilities.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITI.Common.Utilities.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container cannot be null.
        /// </summary>
        internal static string exception_ContainerCannotBeNull {
            get {
                return ResourceManager.GetString("exception_ContainerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression path is null or not a valid expression function.
        /// </summary>
        internal static string exception_ExpressionPathNotValid {
            get {
                return ResourceManager.GetString("exception_ExpressionPathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterExpression cannot be null.
        /// </summary>
        internal static string exception_FilterCannotBeNull {
            get {
                return ResourceManager.GetString("exception_FilterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include path cannot be null or empty string.
        /// </summary>
        internal static string exception_IncludePathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("exception_IncludePathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex*PageCount produce overflow exception.
        /// </summary>
        internal static string exception_InvalidElementsInPage {
            get {
                return ResourceManager.GetString("exception_InvalidElementsInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageCount is less than zero.
        /// </summary>
        internal static string exception_InvalidPageCount {
            get {
                return ResourceManager.GetString("exception_InvalidPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex is less than zero.
        /// </summary>
        internal static string exception_InvalidPageIndex {
            get {
                return ResourceManager.GetString("exception_InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is null.
        /// </summary>
        internal static string exception_ItemArgumentIsNull {
            get {
                return ResourceManager.GetString("exception_ItemArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderByExpression cannot be null.
        /// </summary>
        internal static string exception_OrderByExpressionCannotBeNull {
            get {
                return ResourceManager.GetString("exception_OrderByExpressionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification cannot be null.
        /// </summary>
        internal static string exception_SpecificationIsNull {
            get {
                return ResourceManager.GetString("exception_SpecificationIsNull", resourceCulture);
            }
        }
    }
}
